< {%
    request.variables.set("timestamp", new Date().toISOString());
%}

POST http://127.0.0.1:8080/event
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is a new event created via HTTP POST request.",
  "location": "123 Event St, Event City, EV 12345",
  "dateTime": "{{timestamp}}"
}
