GET http://127.0.0.1:8080/event/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI3ODlAZ21haWwuY29tIiwiZXhwaXJlIjoxNzUzMzUyODk2LCJ1c2VySWQiOjN9.jWYHn1b00gevPjLLrVioPXmMNt9dT9nR9fmK1rYRbOo