< {%
    request.variables.set("timestamp", new Date().toISOString());
%}

POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "email": "user456@gmail.com",
  "password": "This is demo."
}
